import { createRoot } from "react-dom/client";
import "./index.css";
// import App from "./demo/reducer_demo";
// import App from "./demo/ref_demo";
// import App from "./demo/context_demo";
// import App from "./hook_demo/memo_demo";
// import App from "./hook_closure/set_timeout_closure";
// import App from "./hook_closure/use_setInterval_hook";
// import App from "./ts_react/fn_react";
// import App from "./ts_react/ref_ts";
// import App from "./ts_react/props_with_children";
// import App from "./ts_react/css_ts";
// import App from "./ts_react/eventhandler";
import App from "./debug_demo/debug_demo";
createRoot(document.getElementById("root")!).render(<App />);
